using System.Globalization;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

if (args.Length != 2)
{
    Console.Error.WriteLine("Usage: ZemaxMCP.ToolManifestGenerator <tools-source-root> <output-file>");
    return 2;
}

var toolsRoot = Path.GetFullPath(args[0]);
var outputFile = Path.GetFullPath(args[1]);
if (!Directory.Exists(toolsRoot))
{
    Console.Error.WriteLine("Tool source root does not exist: " + toolsRoot);
    return 2;
}

var documents = Directory.GetFiles(toolsRoot, "*.cs", SearchOption.AllDirectories)
    .OrderBy(path => path, StringComparer.OrdinalIgnoreCase)
    .Select(path => new SourceDocument(path, CSharpSyntaxTree.ParseText(File.ReadAllText(path)).GetCompilationUnitRoot()))
    .ToArray();

var context = new SchemaContext(documents);
var tools = new List<GeneratedTool>();
foreach (var document in documents)
{
    foreach (var type in document.Root.DescendantNodes().OfType<ClassDeclarationSyntax>().Where(type => HasAttribute(type.AttributeLists, "ZemaxToolType")))
    {
        foreach (var method in type.Members.OfType<MethodDeclarationSyntax>())
        {
            var attribute = FindAttribute(method.AttributeLists, "ZemaxTool");
            if (attribute == null) continue;
            var name = GetNamedString(attribute, "Name") ?? GetPositionalString(attribute, 0);
            if (string.IsNullOrWhiteSpace(name)) continue;
            var descriptionAttribute = FindAttribute(method.AttributeLists, "Description");
            var description = descriptionAttribute == null ? null : GetPositionalString(descriptionAttribute, 0);
            tools.Add(new GeneratedTool(
                name,
                string.IsNullOrWhiteSpace(description) ? "No additional description is available." : description,
                BuildMethodSchema(method, type, context)));
        }
    }
}

var duplicates = tools.GroupBy(tool => tool.Name, StringComparer.Ordinal).Where(group => group.Count() != 1).ToArray();
if (duplicates.Length > 0)
    throw new InvalidOperationException("Duplicate Worker tool names: " + string.Join(", ", duplicates.Select(group => group.Key)));
if (tools.Count == 0)
    throw new InvalidOperationException("No ZemaxTool methods were found under " + toolsRoot);

var source = new StringBuilder();
source.AppendLine("// <auto-generated />");
source.AppendLine("namespace ZemaxMCP.ToolManifest;");
source.AppendLine();
source.AppendLine("internal static class GeneratedToolManifestData");
source.AppendLine("{");
source.AppendLine("    internal static readonly ToolManifestEntry[] Entries = new ToolManifestEntry[]");
source.AppendLine("    {");
foreach (var tool in tools.OrderBy(tool => tool.Name, StringComparer.Ordinal))
{
    var schemaJson = JsonSerializer.Serialize(tool.Schema);
    source.Append("        new ToolManifestEntry(")
        .Append(Verbatim(tool.Name)).Append(", ")
        .Append(Verbatim(tool.Description)).Append(", ")
        .Append(Verbatim(schemaJson)).AppendLine("),");
}
source.AppendLine("    };");
source.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);
File.WriteAllText(outputFile, source.ToString(), new UTF8Encoding(false));
Console.WriteLine($"Generated static tool manifest with {tools.Count} tools: {outputFile}");
return 0;

static Dictionary<string, object?> BuildMethodSchema(MethodDeclarationSyntax method, TypeDeclarationSyntax declaringType, SchemaContext context)
{
    var properties = new Dictionary<string, object?>(StringComparer.Ordinal);
    var required = new List<string>();
    foreach (var parameter in method.ParameterList.Parameters)
    {
        if (parameter.Type == null || IsCancellationToken(parameter.Type)) continue;
        var schema = context.BuildTypeSchema(parameter.Type, declaringType, new HashSet<string>(StringComparer.Ordinal));
        var descriptionAttribute = FindAttribute(parameter.AttributeLists, "Description");
        var description = descriptionAttribute == null ? null : GetPositionalString(descriptionAttribute, 0);
        if (!string.IsNullOrWhiteSpace(description)) schema["description"] = description;
        if (parameter.Default != null) schema["default"] = ParseDefault(parameter.Default.Value, parameter.Type);
        else required.Add(parameter.Identifier.ValueText);
        properties[parameter.Identifier.ValueText] = schema;
    }

    var result = new Dictionary<string, object?>
    {
        ["type"] = "object",
        ["properties"] = properties,
        ["additionalProperties"] = false
    };
    if (required.Count > 0) result["required"] = required;
    return result;
}

static bool IsCancellationToken(TypeSyntax type) => SimpleTypeName(type) == "CancellationToken";

static object? ParseDefault(ExpressionSyntax expression, TypeSyntax type)
{
    if (expression is LiteralExpressionSyntax literal) return literal.Token.Value;
    if (expression.IsKind(SyntaxKind.DefaultLiteralExpression) || expression.IsKind(SyntaxKind.NullLiteralExpression)) return null;
    if (expression is DefaultExpressionSyntax) return null;
    if (expression is PrefixUnaryExpressionSyntax prefix && prefix.IsKind(SyntaxKind.UnaryMinusExpression) && prefix.Operand is LiteralExpressionSyntax number)
    {
        var raw = "-" + number.Token.ValueText;
        if (long.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out var integer)) return integer;
        if (double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out var floating)) return floating;
    }
    if (expression is MemberAccessExpressionSyntax member) return member.Name.Identifier.ValueText;
    if (expression is IdentifierNameSyntax identifier)
    {
        if (identifier.Identifier.ValueText == "default") return null;
        return identifier.Identifier.ValueText;
    }
    return expression.ToString();
}

static string Verbatim(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";

static AttributeSyntax? FindAttribute(SyntaxList<AttributeListSyntax> lists, string expected)
    => lists.SelectMany(list => list.Attributes).FirstOrDefault(attribute => AttributeName(attribute) == expected);

static bool HasAttribute(SyntaxList<AttributeListSyntax> lists, string expected) => FindAttribute(lists, expected) != null;

static string AttributeName(AttributeSyntax attribute)
{
    var name = attribute.Name.ToString().Split('.').Last();
    return name.EndsWith("Attribute", StringComparison.Ordinal) ? name[..^"Attribute".Length] : name;
}

static string? GetNamedString(AttributeSyntax attribute, string name)
{
    var argument = attribute.ArgumentList?.Arguments.FirstOrDefault(candidate => candidate.NameEquals?.Name.Identifier.ValueText == name);
    return argument == null ? null : GetStringLiteral(argument.Expression);
}

static string? GetPositionalString(AttributeSyntax attribute, int index)
{
    var arguments = attribute.ArgumentList?.Arguments.Where(argument => argument.NameEquals == null && argument.NameColon == null).ToArray();
    return arguments != null && index < arguments.Length ? GetStringLiteral(arguments[index].Expression) : null;
}

static string? GetStringLiteral(ExpressionSyntax expression)
    => expression is LiteralExpressionSyntax literal && literal.IsKind(SyntaxKind.StringLiteralExpression) ? literal.Token.ValueText : null;

static string SimpleTypeName(TypeSyntax type) => type switch
{
    NullableTypeSyntax nullable => SimpleTypeName(nullable.ElementType),
    IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
    GenericNameSyntax generic => generic.Identifier.ValueText,
    QualifiedNameSyntax qualified => SimpleTypeName(qualified.Right),
    AliasQualifiedNameSyntax alias => SimpleTypeName(alias.Name),
    PredefinedTypeSyntax predefined => predefined.Keyword.ValueText,
    _ => type.ToString().TrimEnd('?').Split('.').Last()
};

sealed record SourceDocument(string Path, CompilationUnitSyntax Root);
sealed record GeneratedTool(string Name, string Description, Dictionary<string, object?> Schema);

sealed class SchemaContext
{
    private readonly Dictionary<string, List<TypeDeclarationSyntax>> _types;
    private readonly Dictionary<string, List<EnumDeclarationSyntax>> _enums;

    public SchemaContext(IEnumerable<SourceDocument> documents)
    {
        _types = documents.SelectMany(document => document.Root.DescendantNodes().OfType<TypeDeclarationSyntax>())
            .GroupBy(type => type.Identifier.ValueText, StringComparer.Ordinal)
            .ToDictionary(group => group.Key, group => group.ToList(), StringComparer.Ordinal);
        _enums = documents.SelectMany(document => document.Root.DescendantNodes().OfType<EnumDeclarationSyntax>())
            .GroupBy(type => type.Identifier.ValueText, StringComparer.Ordinal)
            .ToDictionary(group => group.Key, group => group.ToList(), StringComparer.Ordinal);
    }

    public Dictionary<string, object?> BuildTypeSchema(TypeSyntax type, TypeDeclarationSyntax declaringType, HashSet<string> stack)
    {
        if (type is NullableTypeSyntax nullable) return BuildTypeSchema(nullable.ElementType, declaringType, stack);
        if (type is ArrayTypeSyntax array)
            return new Dictionary<string, object?> { ["type"] = "array", ["items"] = BuildTypeSchema(array.ElementType, declaringType, stack) };

        var simple = SimpleTypeName(type);
        if (simple is "string" or "String" or "char" or "Char") return Scalar("string");
        if (simple is "bool" or "Boolean") return Scalar("boolean");
        if (simple is "byte" or "sbyte" or "short" or "ushort" or "int" or "uint" or "long" or "ulong" or "Byte" or "SByte" or "Int16" or "UInt16" or "Int32" or "UInt32" or "Int64" or "UInt64") return Scalar("integer");
        if (simple is "float" or "double" or "decimal" or "Single" or "Double" or "Decimal") return Scalar("number");

        if (type is GenericNameSyntax generic)
        {
            var arguments = generic.TypeArgumentList.Arguments;
            if (simple == "Nullable" && arguments.Count == 1) return BuildTypeSchema(arguments[0], declaringType, stack);
            if (simple is "Dictionary" or "IDictionary" or "IReadOnlyDictionary" && arguments.Count == 2 && SimpleTypeName(arguments[0]) is "string" or "String")
                return new Dictionary<string, object?> { ["type"] = "object", ["additionalProperties"] = BuildTypeSchema(arguments[1], declaringType, stack) };
            if (simple is "List" or "IList" or "IReadOnlyList" or "IEnumerable" or "ICollection" or "IReadOnlyCollection" or "HashSet" && arguments.Count == 1)
                return new Dictionary<string, object?> { ["type"] = "array", ["items"] = BuildTypeSchema(arguments[0], declaringType, stack) };
        }

        var enumType = ResolveEnum(simple, declaringType);
        if (enumType != null)
            return new Dictionary<string, object?> { ["type"] = "string", ["enum"] = enumType.Members.Select(member => member.Identifier.ValueText).ToArray() };

        var modelType = ResolveType(simple, declaringType);
        if (modelType != null) return BuildObjectSchema(modelType, stack);
        return Scalar("object");
    }

    private Dictionary<string, object?> BuildObjectSchema(TypeDeclarationSyntax type, HashSet<string> stack)
    {
        var key = QualifiedTypeName(type);
        if (!stack.Add(key)) return Scalar("object");
        try
        {
            var properties = new Dictionary<string, object?>(StringComparer.Ordinal);
            var required = new List<string>();
            ParameterListSyntax? primaryParameters = type switch
            {
                RecordDeclarationSyntax record => record.ParameterList,
                ClassDeclarationSyntax @class => @class.ParameterList,
                StructDeclarationSyntax @struct => @struct.ParameterList,
                _ => null
            };
            if (primaryParameters != null && primaryParameters.Parameters.Count > 0)
            {
                foreach (var parameter in primaryParameters.Parameters)
                {
                    if (parameter.Type == null) continue;
                    var name = CamelCase(parameter.Identifier.ValueText);
                    var schema = BuildTypeSchema(parameter.Type, type, stack);
                    var descriptionAttribute = FindAttribute(parameter.AttributeLists, "Description");
                    var description = descriptionAttribute == null ? null : GetPositionalString(descriptionAttribute, 0);
                    if (!string.IsNullOrWhiteSpace(description)) schema["description"] = description;
                    if (parameter.Default != null) schema["default"] = ParseDefault(parameter.Default.Value, parameter.Type);
                    else required.Add(name);
                    properties[name] = schema;
                }
            }
            else
            {
                foreach (var property in type.Members.OfType<PropertyDeclarationSyntax>().Where(property => property.Modifiers.Any(SyntaxKind.PublicKeyword)))
                    properties[CamelCase(property.Identifier.ValueText)] = BuildTypeSchema(property.Type, type, stack);
            }

            var result = new Dictionary<string, object?>
            {
                ["type"] = "object",
                ["properties"] = properties,
                ["additionalProperties"] = false
            };
            if (required.Count > 0) result["required"] = required;
            return result;
        }
        finally { stack.Remove(key); }
    }

    private TypeDeclarationSyntax? ResolveType(string name, TypeDeclarationSyntax declaringType)
    {
        var nested = declaringType.Members.OfType<TypeDeclarationSyntax>().FirstOrDefault(type => type.Identifier.ValueText == name);
        if (nested != null) return nested;
        if (!_types.TryGetValue(name, out var candidates)) return null;
        return candidates.Count == 1 ? candidates[0] : candidates.FirstOrDefault(candidate => SameNamespace(candidate, declaringType));
    }

    private EnumDeclarationSyntax? ResolveEnum(string name, TypeDeclarationSyntax declaringType)
    {
        var nested = declaringType.Members.OfType<EnumDeclarationSyntax>().FirstOrDefault(type => type.Identifier.ValueText == name);
        if (nested != null) return nested;
        if (!_enums.TryGetValue(name, out var candidates)) return null;
        return candidates.Count == 1 ? candidates[0] : candidates.FirstOrDefault(candidate => SameNamespace(candidate, declaringType));
    }

    private static bool SameNamespace(SyntaxNode left, SyntaxNode right) => Namespace(left) == Namespace(right);
    private static string Namespace(SyntaxNode node) => node.Ancestors().OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault()?.Name.ToString() ?? string.Empty;
    private static string QualifiedTypeName(TypeDeclarationSyntax type) => Namespace(type) + "." + string.Join(".", type.AncestorsAndSelf().OfType<TypeDeclarationSyntax>().Reverse().Select(candidate => candidate.Identifier.ValueText));
    private static Dictionary<string, object?> Scalar(string type) => new() { ["type"] = type };
    private static string CamelCase(string value) => value.Length == 0 || char.IsLower(value[0]) ? value : char.ToLowerInvariant(value[0]) + value[1..];
}
