<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ZemaxMCP.ClientProxy</AssemblyName>
    <RootNamespace>ZemaxMCP.ClientProxy</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
